// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ConfigRouteRouteImport } from "./routes/config/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ConfigIndexRouteImport } from "./routes/config/index"

const ConfigUpstreamsLazyRouteImport = createFileRoute("/config/upstreams")()
const ConfigSettingsLazyRouteImport = createFileRoute("/config/settings")()
const ConfigProvidersLazyRouteImport = createFileRoute("/config/providers")()
const ConfigPricingLazyRouteImport = createFileRoute("/config/pricing")()
const ConfigLogsLazyRouteImport = createFileRoute("/config/logs")()
const ConfigDashboardLazyRouteImport = createFileRoute("/config/dashboard")()
const ConfigCoreLazyRouteImport = createFileRoute("/config/core")()
const ConfigAgentsLazyRouteImport = createFileRoute("/config/agents")()

const ConfigRouteRoute = ConfigRouteRouteImport.update({
  id: "/config",
  path: "/config",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ConfigRouteRoute,
} as any)
const ConfigUpstreamsLazyRoute = ConfigUpstreamsLazyRouteImport.update({
  id: "/upstreams",
  path: "/upstreams",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/upstreams.lazy").then((d) => d.Route),
)
const ConfigSettingsLazyRoute = ConfigSettingsLazyRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/settings.lazy").then((d) => d.Route),
)
const ConfigProvidersLazyRoute = ConfigProvidersLazyRouteImport.update({
  id: "/providers",
  path: "/providers",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/providers.lazy").then((d) => d.Route),
)
const ConfigPricingLazyRoute = ConfigPricingLazyRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/pricing.lazy").then((d) => d.Route),
)
const ConfigLogsLazyRoute = ConfigLogsLazyRouteImport.update({
  id: "/logs",
  path: "/logs",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() => import("./routes/config/logs.lazy").then((d) => d.Route))
const ConfigDashboardLazyRoute = ConfigDashboardLazyRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/dashboard.lazy").then((d) => d.Route),
)
const ConfigCoreLazyRoute = ConfigCoreLazyRouteImport.update({
  id: "/core",
  path: "/core",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() => import("./routes/config/core.lazy").then((d) => d.Route))
const ConfigAgentsLazyRoute = ConfigAgentsLazyRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() => import("./routes/config/agents.lazy").then((d) => d.Route))

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/config": typeof ConfigRouteRouteWithChildren
  "/config/agents": typeof ConfigAgentsLazyRoute
  "/config/core": typeof ConfigCoreLazyRoute
  "/config/dashboard": typeof ConfigDashboardLazyRoute
  "/config/logs": typeof ConfigLogsLazyRoute
  "/config/pricing": typeof ConfigPricingLazyRoute
  "/config/providers": typeof ConfigProvidersLazyRoute
  "/config/settings": typeof ConfigSettingsLazyRoute
  "/config/upstreams": typeof ConfigUpstreamsLazyRoute
  "/config/": typeof ConfigIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/config/agents": typeof ConfigAgentsLazyRoute
  "/config/core": typeof ConfigCoreLazyRoute
  "/config/dashboard": typeof ConfigDashboardLazyRoute
  "/config/logs": typeof ConfigLogsLazyRoute
  "/config/pricing": typeof ConfigPricingLazyRoute
  "/config/providers": typeof ConfigProvidersLazyRoute
  "/config/settings": typeof ConfigSettingsLazyRoute
  "/config/upstreams": typeof ConfigUpstreamsLazyRoute
  "/config": typeof ConfigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/config": typeof ConfigRouteRouteWithChildren
  "/config/agents": typeof ConfigAgentsLazyRoute
  "/config/core": typeof ConfigCoreLazyRoute
  "/config/dashboard": typeof ConfigDashboardLazyRoute
  "/config/logs": typeof ConfigLogsLazyRoute
  "/config/pricing": typeof ConfigPricingLazyRoute
  "/config/providers": typeof ConfigProvidersLazyRoute
  "/config/settings": typeof ConfigSettingsLazyRoute
  "/config/upstreams": typeof ConfigUpstreamsLazyRoute
  "/config/": typeof ConfigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/config"
    | "/config/agents"
    | "/config/core"
    | "/config/dashboard"
    | "/config/logs"
    | "/config/pricing"
    | "/config/providers"
    | "/config/settings"
    | "/config/upstreams"
    | "/config/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/config/agents"
    | "/config/core"
    | "/config/dashboard"
    | "/config/logs"
    | "/config/pricing"
    | "/config/providers"
    | "/config/settings"
    | "/config/upstreams"
    | "/config"
  id:
    | "__root__"
    | "/"
    | "/config"
    | "/config/agents"
    | "/config/core"
    | "/config/dashboard"
    | "/config/logs"
    | "/config/pricing"
    | "/config/providers"
    | "/config/settings"
    | "/config/upstreams"
    | "/config/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRouteRoute: typeof ConfigRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/config": {
      id: "/config"
      path: "/config"
      fullPath: "/config"
      preLoaderRoute: typeof ConfigRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/config/": {
      id: "/config/"
      path: "/"
      fullPath: "/config/"
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/upstreams": {
      id: "/config/upstreams"
      path: "/upstreams"
      fullPath: "/config/upstreams"
      preLoaderRoute: typeof ConfigUpstreamsLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/settings": {
      id: "/config/settings"
      path: "/settings"
      fullPath: "/config/settings"
      preLoaderRoute: typeof ConfigSettingsLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/providers": {
      id: "/config/providers"
      path: "/providers"
      fullPath: "/config/providers"
      preLoaderRoute: typeof ConfigProvidersLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/pricing": {
      id: "/config/pricing"
      path: "/pricing"
      fullPath: "/config/pricing"
      preLoaderRoute: typeof ConfigPricingLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/logs": {
      id: "/config/logs"
      path: "/logs"
      fullPath: "/config/logs"
      preLoaderRoute: typeof ConfigLogsLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/dashboard": {
      id: "/config/dashboard"
      path: "/dashboard"
      fullPath: "/config/dashboard"
      preLoaderRoute: typeof ConfigDashboardLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/core": {
      id: "/config/core"
      path: "/core"
      fullPath: "/config/core"
      preLoaderRoute: typeof ConfigCoreLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/agents": {
      id: "/config/agents"
      path: "/agents"
      fullPath: "/config/agents"
      preLoaderRoute: typeof ConfigAgentsLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
  }
}

interface ConfigRouteRouteChildren {
  ConfigAgentsLazyRoute: typeof ConfigAgentsLazyRoute
  ConfigCoreLazyRoute: typeof ConfigCoreLazyRoute
  ConfigDashboardLazyRoute: typeof ConfigDashboardLazyRoute
  ConfigLogsLazyRoute: typeof ConfigLogsLazyRoute
  ConfigPricingLazyRoute: typeof ConfigPricingLazyRoute
  ConfigProvidersLazyRoute: typeof ConfigProvidersLazyRoute
  ConfigSettingsLazyRoute: typeof ConfigSettingsLazyRoute
  ConfigUpstreamsLazyRoute: typeof ConfigUpstreamsLazyRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
}

const ConfigRouteRouteChildren: ConfigRouteRouteChildren = {
  ConfigAgentsLazyRoute: ConfigAgentsLazyRoute,
  ConfigCoreLazyRoute: ConfigCoreLazyRoute,
  ConfigDashboardLazyRoute: ConfigDashboardLazyRoute,
  ConfigLogsLazyRoute: ConfigLogsLazyRoute,
  ConfigPricingLazyRoute: ConfigPricingLazyRoute,
  ConfigProvidersLazyRoute: ConfigProvidersLazyRoute,
  ConfigSettingsLazyRoute: ConfigSettingsLazyRoute,
  ConfigUpstreamsLazyRoute: ConfigUpstreamsLazyRoute,
  ConfigIndexRoute: ConfigIndexRoute,
}

const ConfigRouteRouteWithChildren = ConfigRouteRoute._addFileChildren(
  ConfigRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRouteRoute: ConfigRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
